name: Update timetable

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape timetable
    runs-on: ubuntu-latest
    outputs:
      repo-updated: ${{ steps.git-step.outputs.updated }}

    env:
      LOGIN: ${{ secrets.STUDENT_ID }}
      PASSWORD: ${{ secrets.STUDENT_PASSWORD }}

    steps:
      - name: Show secrets
        run: |
          echo $LOGIN
          echo $PASSWORD

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install
          pnpm lint
          pnpm fmt

      - name: Setup playwright
        run: pnpx playwright install --with-deps

      - name: Install xvfb if not exists
        run: |
          if ! command -v xvfb-run &> /dev/null
          then
            sudo apt-get install -y xvfb
          else
            echo "xvfb already installed"
          fi

      - name: Run the scraper
        run: xvfb-run pnpm start

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: dest
          repository: mad-maids/wiut-data
          ref: main
          fetch-depth: 0

      - name: Remove old data if exists
        run: |
          if [ -d dest/timetable ]; then
            rm -rf dest/timetable
          else
            echo "No old data found"
          fi

      - name: Copy data to destination
        run: cp -r data dest/timetable

      - name: Upload all changes to GIT
        id: git-step
        working-directory: dest
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          [[ -z $(git status -uno --porcelain) ]] && echo "No updates detected, no need for push" && exit 0;
          git commit -m "update timetable $(date -u)"
          git push origin main --force
          echo "::set-output name=updated::yes"

#  upload:
#    name: Upload data to latest release
#    runs-on: ubuntu-latest
#    needs: scrape
#    if: ${{ needs.scrape.outputs.repo-updated }}
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          ref: "main"
#      - name: Prepare zip file
#        run: |
#          mkdir assets
#          zip --junk-paths -r assets/data.zip data
#      - name: Get release ID
#        id: getid
#        run:   |
#          rel_id=$(curl -sL -H 'Authorization: token ${{ secrets.PAT }}' https://api.github.com/repos/mad-maids/maid.felix/releases/latest | jq -r '.id')
#          echo "::set-output name=rel_id::$rel_id"
#      - name: Remove release asset
#        uses: flcdrg/remove-release-asset-action@v1.0.3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          release_id: ${{ steps.getid.outputs.rel_id }}
#          asset_name: 'data.zip'
#      - name: Get upload URL
#        id: geturl
#        run:   |
#          upload_url=$(curl -sL -H 'Authorization: token ${{ secrets.PAT }}' https://api.github.com/repos/mad-maids/maid.felix/releases/latest | jq -r '.upload_url')
#          echo "::set-output name=upload_url::$upload_url"
#      - name: Upload release asset
#        id: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.geturl.outputs.upload_url }}
#          asset_path: ./assets/data.zip
#          asset_name: data.zip
#          asset_content_type: application/zip
